# Generated by Django 2.2.15 on 2021-03-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=50, verbose_name='To')),
                ('sender', models.CharField(max_length=50, verbose_name='from')),
                ('mes', models.TextField(verbose_name='message')),
            ],
        ),
    ]
