# Generated by Django 2.2.15 on 2021-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailbox',
            old_name='mes',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='to',
            field=models.CharField(max_length=50, verbose_name='to'),
        ),
    ]
