# Generated by Django 2.2.15 on 2021-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210317_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='sub',
            field=models.CharField(max_length=50, null=True, verbose_name='subject'),
        ),
    ]
